routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','client\HomeController@home');
Route::get('/auth/login','Auth\LoginController@index')->name('login');
Route::get('/create-account','Auth\RegisterController@index');

Route::get('/products','client\ProductsController@getProducts');

Route::get('/product/{slug}','client\HomeController@getproduct');
Route::get('/products/category/{slug}','client\HomeController@filter_by_categories');

Route::post('/new/create','Auth\RegisterController@create');
Route::post('/user/login','Auth\LoginController@login');
Route::post('/logout','Auth\LoginController@logout');


Route::get('/dashboard','dashboard\DashboardController@index')->middleware('auth');
Route::get('/dashboard/physical/category','dashboard\DashboardController@physical_category')->middleware('auth');
Route::get('/dashboard/physical/category/sub/{sub_id}','dashboard\DashboardController@get_sub_category')->middleware('auth');
Route::post('/physical/category/create','dashboard\CategoryController@store')->middleware('auth');
Route::post('/physical/category/edit/{id}','dashboard\CategoryController@update')->middleware('auth');
Route::get('/physical/category/delete/{id}','dashboard\CategoryController@destroy')->middleware('auth');
Route::get('/dashboard/physical/sub-category','dashboard\DashboardController@physical_sub_category')->middleware('auth');
Route::post('/dashboard/physical/sub-category','dashboard\CategoryController@store_sub')->middleware('auth');

Route::get('/dashboard/physical/product-lists','dashboard\DashboardController@product_lists')->middleware('auth');

Route::get('/dashboard/physical/create-product','dashboard\DashboardController@create_product')->middleware('auth');
Route::post('/dashboard/physical/create-product','dashboard\DashboardController@store_product')->middleware('auth');
Route::post('/dashboard/physical/product/update/{id}','dashboard\DashboardController@update_product')->middleware('auth');
Route::get('/dashboard/physical/edit/{id}','dashboard\ProductController@show')->middleware('auth');
Route::get('/dashboard/physical/product/{slug}','dashboard\ProductController@details')->middleware('auth');
Route::get('/product/destroy/{id}','dashboard\ProductController@destroy')->middleware('auth');
Route::post('/product/variation/create/{id}','dashboard\VariationController@store')->middleware('auth');
Route::get('/dashboard/physical/product/variation/add/{id}','dashboard\VariationController@add')->middleware('auth');
Route::post('/dashboard/physical/product/variation/create/{id}','dashboard\VariationController@insert')->middleware('auth');

Route::post('/physical/category/variation/create','dashboard\VariationController@create')->middleware('auth');
Route::get('/product/variation/destroy/{id}','dashboard\VariationController@destroy')->middleware('auth');





Route::post('/dashboard/physical/upload-image','dashboard\DashboardController@uploadImage')->middleware('auth');
Route::get('/dashboard/digital/create-product','dashboard\DashboardController@create_product')->middleware('auth');
Route::get('/dashboard/sub-category','dashboard\DashboardController@sub-category')->middleware('auth');
Route::get('/dashboard/all-products','dashboard\DashboardController@sub-category')->middleware('auth');
Route::get('/dashboard/create-product','dashboard\DashboardController@create-product')->middleware('auth');

Route::get('/category/{category}','client\CategoryController@loadProducts');


Route::get('/getSubcategory/{id}','dashboard\DashboardController@getSubCategory')->middleware('auth');
Route::post('/images-save/{id}', 'dashboard\DashboardController@store_product_images');
Route::post('/images-delete', 'UploadImagesController@destroy');
Route::get('/images-show', 'UploadImagesController@index');


Route::get('/dashboard/sales/orders','Dashboard\OrdersController@index')->middleware('auth');
Route::get('/dashboard/sales/transactions','Dashboard\TransactionsController@index')->middleware('auth');


Route::get('/dashboard/coupons','Dashboard\DashboardController@index')->middleware('auth');
Route::get('/dashboard/create','Dashboard\DashboardController@show')->middleware('auth');

Route::get('/dashboard/users','Dashboard\UsersController@index')->middleware('auth');
Route::get('/dashboard/new','Dashboard\UsersController@create')->middleware('auth');

Route::get('/dashboard/settings','Dashboard\SettingsController@index')->middleware('auth');
Route::get('/dashboard/physical/attributes','Dashboard\SettingsController@attributes')->middleware('auth');
Route::post('/dashboard/physical/product/attributes/create','dashboard\SettingsController@createAttribute')->middleware('auth');


Route::resource('/dashboard/brands','BrandController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Product extends Model
{
    //
    use HasSlug;


    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom(['title','stock_id'])
            ->saveSlugsTo('slug');
    }

    public function categories(){
    return $this->belongsToMany(Category::class);
    }
    public function variations(){
        return $this->belongsToMany(Variation::class);
    }
}

app/Http/Controllers/client/ProductsController.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use App\Product;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    //
    public function getProducts(Request $request){
        $products = Product::latest()->get();

        return view('client.products')->with('products',$products);

    }
}

app/Http/Controllers/dashboard/ProductController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use App\Product;
use App\Variation;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        $categories = Category::with('ancestors')->get()->toTree();
            return view('dashboard.products.forms.edit-product')->with(['product'=>$product,'categories'=>$categories]);
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }
    public function details(Request $request){

        $product = Product::where('slug',$request->slug)->first();
        return view('dashboard.products.physical.details')->with(['product'=>$product]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        if($product->delete()) {
            $variation = Variation::where('product_id',$id);
            $variation->delete();
            return response()->json([
                "message"=>true
            ]);
            }
        //
    }
}

resources/views/dashboard/products/physical/attributes.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/13/2020
 * Time: 4:35 PM
 */
?>
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/11/2020
 * Time: 3:04 PM
 */
?>
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/11/2020
 * Time: 3:02 PM
 */
?>
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')


    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Add Attributes</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <form method="post" action="/dashboard/physical/product/attributes/create" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <div  class="variation_form">
                        <label>Attribute</label>
                        <br/>
                        <small>Add product attribute</small>

                        <div class="form-group">
                            <label for="attribute_name">Attribute name</label>
                            <input required name="att_name" id="variation_name" type="text" class="form-control">
                        </div>
                        <button  type="submit" class="btn btn-flat btn-secondary btn-sm">Save</button>
                    </div>
                    <br/>

                    <button style="display: none" onclick="addFields()" type="button" class="btn btn-warning btn-flat"><i class="fa fa-plus"></i>&nbsp;Add options set </button>

                </div>
            </form>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach(\App\Attribute::all() as $key=>$attr)
                    <tr>
                        <th scope="row">{{$key+1}}</th>
                        <td>{{$attr->name}}</td>
                        <td>
                            <a href="#!" class="btn btn-sm btn-success"><i class="fa fa-plus-square"></i> </a>
                        </td>

                    </tr>
                @endforeach

                </tbody>
            </table>

        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/dashboard/products/physical/brands.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/11/2020
 * Time: 2:52 PM
 */
?>
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Brands</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="link-color" href="#">Home</a></li>
                    <li class="breadcrumb-item active">brands</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Popular brands</h3>
            <a href="/dashboard/brands/create"  class="btn btn-flat float-right btn-warning">Add Brand&nbsp;<i class="fa fa-eye"></i> </a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Logo</th>
                    <th>Name</th>

                    <th>Actions</th>

                </tr>
                </thead>
                <tbody>
                @foreach($brands as $brand)
                    <tr id="row{{$brand->id}}">
                        <td>
                            @if($brand->logo!=='noimage.jpg')
                                <img style="max-height: 30px" src="{{asset('/brands/resized/'.$brand->logo)}}"/>
                            @else
                                <img style="max-height: 30px" src="{{asset('/images/placeholder.png')}}"/>
                            @endif
                        </td>
                        <td>
                            {{$brand->name}}
                        </td>

                        <td >
                            <a data-toggle="modal" data-target="#modal-category{{$brand->id}}"   href="#" class="btn btn-sm btn-success"><i  class="fa fa-edit"></i></a>
                            <a onclick='

                                    if(confirm("Are you sure you want to delete?")){
                                    $.ajax({
                                    method:"get",
                                    url:"/dashboard/brands/destroy/{{$brand->id}}",
                                    success:function(resp) {
                                    if(resp.message){
                                    $("#row{{$brand->id}}").hide()

                                    }
                                    console.log(resp)
                                    }
                                    })
                                    }


                                    ' href="#!"  class="btn btn-sm btn-danger">  <i  class="fa fa-trash"></i></a>
                        </td>

                    </tr>
                    {{--Edit category modal--}}
                    <div  class="modal fade" id="modal-category{{$brand->id}}">
                        <div class="modal-dialog">
                            <div style="border-radius: 0px !important;" class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Edit {{$brand->name}}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form enctype="multipart/form-data"  method="post" action="{{route('brands.update',$brand->id)}}">
                                    <div class="modal-body">

                                        @csrf
                                        <div class="form-group">
                                            <label for="brand-name{{$brand->id}}">Brand Name</label>
                                            <input value="{{$brand->name}}" name="brand" class="form-control" type="text" id="brand-name{{$brand->id}}" placeholder="category name">
                                            @if ($errors->has('name'))
                                                <div class="invalid-feedback">
                                                    {{ $errors->first('name') }}
                                                </div>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                            <label for="imageFile{{$brand->id}}">Brand Logo <small>optional</small></label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input name="brand_logo" type="file" class="custom-file-input" id="imageFile{{$brand->id}}">
                                                    <label class="custom-file-label" for="imageFile">Choose file</label>
                                                </div>
                                                <div class="input-group-append">
                                                    <span class="input-group-text" id="">Upload</span>
                                                </div>
                                            </div>
                                            <br/>
                                            <img style="max-height: 30px" src="{{asset('/brands/resized/'.$brand->logo)}}"/>
                                        </div>

                                    </div>
                                    <div class="modal-footer justify-content-end">

                                        <button type="submit" class="btn float-right btn-flat btn-warning btn-primary">Save changes</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <!-- /.modal -->
                @endforeach


            </table>
        </div>
    </div>
@stop

@section('content')

    <!-- /.row -->

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/dashboard/products/physical/details.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/13/2020
 * Time: 8:19 AM
 */
?>
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/11/2020
 * Time: 3:04 PM
 */
?>
<?php
/**
 * Created by PhpStorm.
 * User: _ck_
 * Date: 3/11/2020
 * Time: 3:02 PM
 */
?>
@extends('adminlte::page')

@section('title', $product->title)

@section('content_header')

@stop

@section('content')


    <div class="card">
        <div class="card-header">
            <h5 class="card-title text-bold">{{$product->title}}</h5>
            @if($product->product_type=='variable-product')
            <a href="/dashboard/physical/product/variation/add/{{$product->id}}"  class="btn btn-flat btn-sm float-right btn-warning">Add Variation&nbsp;</a>
                @endif
        </div>
        <!-- /.card-header -->
        <div class="card-body">











            <div class="row">
                <div class="col-lg-6">
                    <div class="card" style="width: 100%;">

                        <div class="card-body">

                            <table class="table table-striped">

                                <tbody>
                                <br/>
                                <tr>
                                    <th scope="row">Item cost</th>
                                    <td>{{number_format($product->cost_price)}}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Selling price</th>
                                    <td>{{number_format($product->selling_price)}}</td>
                                </tr>

                                </tbody>
                            </table>

                        </div>

                        <div class="card-body">
                            <h5  class="card-title text-bold">Features</h5>
                            <p class="card-text">{!! $product->features !!}</p>
                            <h5  class="card-title text-bold">Description</h5>
                            <p class="card-text">{!! $product->description !!}</p>
                            <a href="#" class="card-link">Card link</a>
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img  src="/product_images/original/{{$product->featured_image}}" class="card-img-top" alt="...">
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/dashboard/products/physical/list-physical-products.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Physical Products</h3>
            <a href="/dashboard/physical/create-product"  class="btn btn-flat float-right btn-warning">Add New Product&nbsp;<i class="fa fa-plus-circle"></i> </a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Product Image</th>
                    <th>Product Name</th>
                    <th>Category</th>
                    <th>Price&nbsp;(Ksh)</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>

                @foreach($products as $product)
                <tr id="row{{$product->id}}">
                    <td>
                        <img style="max-height: 55px"  src="{{asset("product_images/resized/$product->featured_image")}}">
                    </td>
                    <td>
                        {{$product->title}}
                    </td>
                    <td>
                        @if($product->category_id!==null)
                     {{\App\Category::find($product->category_id)->name}}
                            @else
                          -

                            @endif
                    </td>
                    <td>

                        @if($product->product_type=='variable-product')

                            {{ collect(\App\Variation::where('product_id',$product->id)->get())->min('price')}}  -   {{ collect(\App\Variation::where('product_id',$product->id)->get())->max('price')}}

                            {{--<span class="badge badge-secondary">Variable product</span>--}}

                            @else
                            {{number_format($product->selling_price)}}
                            @endif

                    </td>
                    <td>
                        <a class="btn btn-sm btn-info" href="/dashboard/physical/product/{{$product->slug}}"><i class="fa fa-eye"></i> </a>
                        <a href="/dashboard/physical/edit/{{$product->id}}" class="btn btn-sm btn-success"><i  class="fa fa-edit"></i></a>
                        <a href="#" onclick="

                        if(confirm('Are you sure')){
                            $.ajax({
                            method:'GET',
                            url:'/product/destroy/{{$product->id}}',
                                success:function(resp) {
                                $('#row{{$product->id}}').hide();
                                  console.log(resp)
                                }
                            })
                        }

                            " class="btn btn-sm btn-danger">  <i  class="fa fa-trash"></i></a>
                    </td>

                </tr>
           @endforeach
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <div  class="modal fade" id="modal-category">
        <div class="modal-dialog">
            <div style="border-radius: 0px !important;" class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create New Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label>Select Category</label>
                            <select class="form-control">
                                <option selected disabled>--select--</option>
                                <option>option 2</option>
                                <option>option 3</option>
                                <option>option 4</option>
                                <option>option 5</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="cat-name">Sub-Category Name</label>
                            <input class="form-control" type="text" id="cat-name" placeholder="category name">
                        </div>

                    </form>
                </div>
                <div class="modal-footer justify-content-end">

                    <button type="button" class="btn float-right btn-flat btn-warning btn-primary">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link rel="stylesheet" href="/public/css/dataTables.bootstrap4.css">
@stop

@section('js')
    <script src="/js/jquery.dataTables.js"></script>
    <script src="/js/dataTables.bootstrap4.js"></script>
    <script>
        $("#example1").DataTable();
    </script>
@stop